### ISSUE TITLE
Built in Packages

### ISSUE THREAD

**Issue by donatj** [cespare/deplist#5]
Would it be possible to add a flag to allow the listing of the packages built into go along side of these, to get me an idea of the **entire** list of imports? For example "fmt" or "net/url".

**Comment by cespare** [comment]
If you want all recursive dependencies, you can do that easily enough with `go list`:

    go list -f '{{ join .Deps "\n" }}' yourpkg

**Comment by donatj** [comment]
Oh, interesting.  This is actually entirely what I wanted. Thanks.

**Comment by cespare** [comment]
Added `-std` anyway in 80d05a4ad8d207aad63be15875943657a25a5e07 ;)
